title: Hello, world! I'm shanks0739
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: shanks0739 # add your name
author-img: shanks0739.jpg # add your photo
about-author: I am a c++ developer focusing on rear end development. Always hungry to keep learning. # add description
#twitter: # add your Twitter handle
#facebook: # add your Facebook handle
github: shanks0739 # add your Github handle
email: lzw0739@163.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
